######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 27 00:04:36 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += cubemodel.h cubewidget.h mainwindow.h
SOURCES += cubemodel.cpp cubewidget.cpp mainwindow.cpp main.cpp
FORMS += mainwindow.ui
